# Generated by Django 4.2.3 on 2023-07-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hw_ten_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hw_ten_app.author"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(to="hw_ten_app.tag"),
        ),
    ]
